install:
  - echo install
  - cd C:\Qt\
  - appveyor DownloadFile "https://www.sfml-dev.org/files/SFML-2.5.1-windows-gcc-7.3.0-mingw-32-bit.zip" -FileName "sf.zip"
  - 7z x sf.zip > nul
  - ren SFML-2.5.1 sfml
  - cd C:\projects\djog-unos-2018
  - set QTDIR=C:\Qt\5.11\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;C:\Qt\sfml\bin
  
build_script:
  - qmake djog_unos_2018.pro
  - mingw32-make

test_script:
  - dir
  - cd release
  - djog_unos_2018.exe --short
